### ISSUE TITLE
On google colab

### ISSUE THREAD

**Issue by firmai** [austinjhunt/msci_esg#1]
Hi man, thanks for the cool package, I have been looking at executing your work on google colab. This is probably the closest I have come to getting it to work, could you perhaps let me know how you think this can be run, I have linked to an editable notebook. https://colab.research.google.com/drive/1KkRB3W1yV26AsMNJxA8-WWbs7FPeoyCh?usp=sharing 

![image](https://user-images.githubusercontent.com/26666267/110309388-32c09c00-7ff9-11eb-972a-f86149827a60.png)

**Comment by austinjhunt** [comment]
Hi @firmai, I dug into this and realized that the ESG Ratings Corporate Search Tool that this package scrapes unfortunately does not have any data on Apple, seen here: https://www.msci.com/our-solutions/esg-investing/esg-ratings/esg-ratings-corporate-search-tool/issuer/apple-inc/IID000000002135451

To address this, I've updated the documentation to use TSLA as the example stock, and I'm updating the exception handling to provide a more informative message when a KeyError or NoSuchElementException is reached, saying that this given stock may not have data on the Corporate Search Tool. 

Thank you for creating this issue! It's cool to see someone using the project!

**Comment by austinjhunt** [comment]
Updated example, first attempt is using "AAPL" as the symbol argument, second is using "TSLA" as the symbol argument: 

```
(venv) Austins-iMac:TESTING huntaj$ python test.py 
MSCI ESG Ratings Corporate Search Tool may not have data for the stock AAPL.  To verify this, open https://www.msci.com/our-solutions/esg-investing/esg-ratings/esg-ratings-corporate-search-tool and search for your stock to see if the resulting page contains data.
average
{}
(venv) Austins-iMac:TESTING huntaj$ python test.py 
average
{'rating-paragraph': 'Tesla is average among 40 companies in the automobiles industry.', 'rating-history-paragraph': "Tesla's rating remains unchanged since April, 2019.", 'current': {'esg_rating': 'a', 'esg_category': 'average'}, 'history': {'jul-17': 'aaa', 'apr-18': 'aa', 'aug-18': 'aa', 'apr-19': 'a', 'apr-20': 'a'}}
```
```

**Comment by firmai** [comment]
@austinjhunt thanks for the quick update, I am looking forward to playing around with the data, cheers.
